name: Deployment
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: false
      - name: Copy build to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build"
          target: ${{ secrets.REMOTE_PATH }}
      - run: echo "This job's status is ${{ job.status }}."
