name: Deployment
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: false
      - name: Copy folder content recursively to vps
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: ${{ secrets.REMOTE_PATH }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
      - run: echo "This job's status is ${{ job.status }}."
